### ISSUE TITLE
Error serving disconnected mount

### ISSUE THREAD

**Issue by anacrolix** [anacrolix/dms#18]
```
23:58:12 server.go:1092: http: panic serving 192.168.1.3:46673: readdirent: input/output error
goroutine 2554901 [running]:
net/http.func·009()
        /home/matt/src/go/src/pkg/net/http/server.go:1091 +0xc0
bitbucket.org/anacrolix/dms/dlna/dms.(*Server).readContainer(0xc21007f780, 0x7fffce3df7dd, 0xa, 0xc21023d5c0, 0x1, ...)
        /home/matt/gopath/src/bitbucket.org/anacrolix/dms/dlna/dms/dms.go:372 +0x167
bitbucket.org/anacrolix/dms/dlna/dms.(*Server).contentDirectoryResponseArgs(0xc21007f780, 0xc2101ce61e, 0x10, 0x1, 0xc2101ce631, ...)
        /home/matt/gopath/src/bitbucket.org/anacrolix/dms/dlna/dms/dms.go:467 +0x245
bitbucket.org/anacrolix/dms/dlna/dms.func·021(0x0, 0x0)
        /home/matt/gopath/src/bitbucket.org/anacrolix/dms/dlna/dms/dms.go:649 +0x10b
bitbucket.org/anacrolix/dms/dlna/dms.func·022(0x7f9e7cf2dab8, 0xc2101876e0, 0xc2100beea0)
        /home/matt/gopath/src/bitbucket.org/anacrolix/dms/dlna/dms/dms.go:668 +0x43a
net/http.HandlerFunc.ServeHTTP(0xc210036dc0, 0x7f9e7cf2dab8, 0xc2101876e0, 0xc2100beea0)
```

The `-path` corresponds to a mount that was disconnected without unmounting.

---
- Bitbucket: https://bitbucket.org/anacrolix/dms/issue/18
- Originally reported by: Matt Joiner
- Originally created at: 2013-09-17T17:21:54.706

**Comment by anacrolix** [comment]
_From Matt Joiner on 2013-09-18 08:02:29+00:00_

Fixed by b73cfb5b8a8c
